### ISSUE TITLE
[Suggestion] Better description how to use for average users

### ISSUE THREAD

**Issue by Eiion** [SoulxluoS/cem_Fork#10]
**Version**

- [x] I am using the latest version of CEM

**Describe the bug**

I cannot get your mods to run (cemFork in conjunction with your Fresh-Animations-CEM-fork). As recommended I also went ahead and got [entitytexturefeatures](https://modrinth.com/mod/entitytexturefeatures) as well as [animatica](https://modrinth.com/mod/animatica) (though the latter is deactivated as it's not available for v1.19.3, yet).

**Expected behavior**

Start the game and enjoy new mob animations.

**Screenshots**

![image](https://user-images.githubusercontent.com/18130829/207995683-009e7a09-5ade-48fe-b65d-bd5a20bb3fbd.png)

**Desktop (please complete the following information):**

 - OS: Win 10 Pro
 - Java Version: Eclipse Adoptium/jdk-17.0.1.12
 - Minecraft Version: 1.19.3

**Additional context**

Considering there's no real description (not that I could identify one - the current "How to use") is extremely bare bones and to no use for me, I'd like to kindly ask for a slightly more detailed description on how to get things working, so the average Minecraft player has a better chance to either get it working themselves. Either that or be able to recognize their errors themselves.
Also, the linked discord to me looks like it's the discord for the original mod that you're modifying so I'm not 100% comfortable going to ask for help there when it's not their work I'm having troubles with.

Anyways, if you need help to write up a better "How to use" text after explaining it to me I'm absolutely willing to help you with that if needed.

EDIT: I guess I found the issue after finding your [closed issue ](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17) and also realising that the [Fresh-Animations-CEM-fork](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork) needs to go into the resource pack folder instead of the mod folder. A vital piece of information.

As a solution to this issue I'd like to propose to add one sentence each readme.md to cemForm and Fresh-Animations-CEM-fork: "Put cemFork in your mod folder." and "Put Fresh-Animations-CEM-fork in your resource pack folder (also check this [FAQ post](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17)." respectively.
Thanks for considering.

**Comment by SoulxluoS** [comment]
😉
