### ISSUE TITLE
[BUG] Fresh Animations Mobs Invisible with Latest Iris

### ISSUE THREAD

**Issue by JasonHorkles** [SoulxluoS/cem_Fork#12]
**Version**

- [X] I am using the latest version of CEM

**Describe the bug**

Mobs appear to be invisible using your Fresh Animations CEM resource pack fork, and I imagine it's because this mod has to do with rendering stuff which Iris has changed

**Expected behavior**

The mobs shouldn't be invisible

**Screenshots**

w/ resource pack
![image](https://user-images.githubusercontent.com/51760372/218234258-4c2ff07a-4508-45ea-8c74-c185fa24b79f.png)

w/o resource pack
![image](https://user-images.githubusercontent.com/51760372/218234294-6549a223-85af-46e2-bb4e-b8302241898b.png)

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Java Version: 17.0.1
 - Minecraft Version: 1.19.3

**Additional context**

Could be a problem with the resource pack but I imagine it's the mod itself

**Comment by SoulxluoS** [comment]
Fork no compatible with sodium 0.4.9 and iris  1.5.2, reverting back to 0.4.8 and 1.5.1 fixed it.

Wait CEM update from [dorianpb](https://github.com/dorianpb/cem) or a CEM release from [Traben.](https://discord.com/invite/rURmwrzUcz)

**Comment by JasonHorkles** [comment]
Is this something Iris/Sodium needs to fix then or is this just going to no longer work going forward?

**Comment by SoulxluoS** [comment]
Wait CEM update from [dorianpb](https://github.com/dorianpb/cem) or a CEM release from [Traben.](https://discord.com/invite/rURmwrzUcz)

**Comment by JasonHorkles** [comment]
Ah yeah I found the [upstream issue](https://github.com/dorianpb/cem/issues/115)
Thanks!

**Comment by EGOIST1372** [comment]
@YoungSoulluoS hello cem got updated for new sodium

**Comment by EGOIST1372** [comment]
@YoungSoulluoS also I have a question
does your fork going to be merged with official version or not?

**Comment by SoulxluoS** [comment]
> @YoungSoulluoS also I have a question
> 
> does your fork going to be merged with official version or not?

Hi, yes, I can do it)
