### ISSUE TITLE
[BUG] issue

### ISSUE THREAD

**Issue by Olinus10** [SoulxluoS/cem_Fork#13]
**Version**

- [x] I am using the latest version of CEM

**Describe the bug**

All mobs turn invis with CEM texturepacks in the latest version of using sodium etc

**Expected behavior**

For mobs not to be invis

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Java Version: JDK 17
 - Minecraft Version:  1.19.3

**Additional context**
The original CEM has been updated to the 0.7.2 version, perhaps to fix compatibility this needs to be updated as well

**Comment by SoulxluoS** [comment]
CEM 0.7.2 have bug with armor, not visible. Wait update.

**Comment by FlatBoulders** [comment]
Update fixes the issue: [changelog](https://modrinth.com/mod/cem/version/0.7.3)

> CEM 0.7.2 have bug with armor, not visible. Wait update.

**Comment by Plexxl** [comment]
fixed in [0.7.3](https://modrinth.com/mod/cem/version/0.7.3)

> CEM 0.7.2 have bug with armor, not visible. Wait update.

**Comment by SoulxluoS** [comment]
> fixed in [0.7.3](https://modrinth.com/mod/cem/version/0.7.3)
> 
> > CEM 0.7.2 have bug with armor, not visible. Wait update.

Hi, doing already

**Comment by SoulxluoS** [comment]
https://github.com/YoungSoulluoS/cemFork/releases
