### ISSUE TITLE
[BUG] issue

### ISSUE THREAD

**Issue by Kaiji-Key** [SoulxluoS/cem_Fork#15]
**Version**

- [/] I am using the latest version of CEM

**Describe the bug**

Put simply, the horses, donkeys, mules, and sheep are all completely broken. I am not sure if it affects any other mobs currently.

**Expected behavior**

I expected the animals... to not look possessed?

**Screenshots**

Please post screenshots of what the model looks like in this mod and in Optifine

**Desktop (please complete the following information):**

 - OS: Mac
 - Java Version: 17
 - Minecraft Version: 1.19.3

**Additional context**

**Comment by Kaiji-Key** [comment]
I can share screenshots if needed.

**Comment by SoulxluoS** [comment]
Texturepack?

**Comment by Kaiji-Key** [comment]
> Texturepack?

Err, I’m not sure what you mean by this.

The horses and sheep all have their heads down below their legs, and their bodies are tilted down a little bit.

**Comment by SoulxluoS** [comment]
What texture pack do you use? Freah Animations or?


> > Texturepack?
> 
> Err, I’m not sure what you mean by this.
> 
> The horses and sheep all have their heads down below their legs, and their bodies are tilted down a little bit.

**Comment by Kaiji-Key** [comment]
> What texture pack do you use? Freah Animations or?
> 
> > > Texturepack?
> > 
> > 
> > Err, I’m not sure what you mean by this.
> > The horses and sheep all have their heads down below their legs, and their bodies are tilted down a little bit.

I’m using both of the Fresh Animations packs. There’s one with an Iron Golem face on it, and one with a Villager Face on it.

**Comment by Kaiji-Key** [comment]
> > What texture pack do you use? Freah Animations or?
> > > > Texturepack?
> > > 
> > > 
> > > Err, I’m not sure what you mean by this.
> > > The horses and sheep all have their heads down below their legs, and their bodies are tilted down a little bit.
> 
> I’m using both of the Fresh Animations packs. There’s one with an Iron Golem face on it, and one with a Villager Face on it.

I have a few other texture packs enabled, but none of them affect the horses or sheep.

**Comment by SoulxluoS** [comment]
Ok, read  https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17

> > > What texture pack do you use? Freah Animations or?
> > > > > Texturepack?
> > > > 
> > > > 
> > > > Err, I’m not sure what you mean by this.
> > > > The horses and sheep all have their heads down below their legs, and their bodies are tilted down a little bit.
> > 
> > 
> > I’m using both of the Fresh Animations packs. There’s one with an Iron Golem face on it, and one with a Villager Face on it.
> 
> I have a few other texture packs enabled, but none of them affect the horses or sheep.

**Comment by Kaiji-Key** [comment]
> Ok, read [YoungSoulluoS/Fresh-Animations-CEM-fork#17](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17)
> 
> > > > What texture pack do you use? Freah Animations or?
> > > > > > Texturepack?
> > > > > 
> > > > > 
> > > > > Err, I’m not sure what you mean by this.
> > > > > The horses and sheep all have their heads down below their legs, and their bodies are tilted down a little bit.
> > > 
> > > 
> > > I’m using both of the Fresh Animations packs. There’s one with an Iron Golem face on it, and one with a Villager Face on it.
> > 
> > 
> > I have a few other texture packs enabled, but none of them affect the horses or sheep.

I have both of the Fresh Animation forks, all five of the additional mods, and the CEM fork. I suppose it could be an incompatible mod, so I can check for that. 

It just makes no sense that every mob works great except for the sheep and horse variants.
