### ISSUE TITLE
Sheep Model Bugged

### ISSUE THREAD

**Issue by TrayCrafty** [SoulxluoS/cem_Fork#16]
Sheep model bugged, Custom Entity Models and Entity Textures Features installed. Not sure if its conflicting with any of the other mods i have installed. Any suggestions for a fix?

![Mod Folder ss](https://user-images.githubusercontent.com/63635468/222933704-bc627786-527b-4b9b-bd4e-9ef2917769ef.png)

https://user-images.githubusercontent.com/63635468/222934131-01b34a78-ebd1-418a-a67c-ef5b423d5863.mp4

**Comment by SoulxluoS** [comment]
> Sheep model bugged, Custom Entity Models and Entity Textures Features installed. Not sure if its conflicting with any of the other mods i have installed. Any suggestions for a fix?
> 
> 
> 
> 
> 
> ![Mod Folder ss](https://user-images.githubusercontent.com/63635468/222933704-bc627786-527b-4b9b-bd4e-9ef2917769ef.png)
> 
> 
> 
> https://user-images.githubusercontent.com/63635468/222934131-01b34a78-ebd1-418a-a67c-ef5b423d5863.mp4
> 
> 
> 
> 

Hi, delete mod **cem 0.7.3 1.19** and read https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17
