### ISSUE TITLE
[BUG] crash

### ISSUE THREAD

**Issue by yahi-ko** [SoulxluoS/cem_Fork#17]
**Version**
VERSION 0.7.1 s7 to s10
- [ ] I am using the latest version of CEM

**Describe the bug**

Having both effective and cem crashes instantly without even loading minecraft

**Expected behavior**

**Screenshots**

Please post screenshots of what the model looks like in this mod and in Optifine

**Desktop (please complete the following information):**

 - OS: Win11
 - Java Version: JDK 17
 - Minecraft Version: 1.19.2 Fabric

**Additional context**
i tested it with s10 first then kept downgrading until i reach s7 and it still crashes

**Comment by yahi-ko** [comment]
this is the logs for reference https://paste.ee/p/RWusv

**Comment by SoulxluoS** [comment]
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17
