### ISSUE TITLE
Upload on CurseForge?

### ISSUE THREAD

**Issue by Wubzzz1337** [SoulxluoS/cem_Fork#18]
Hi, just quick question.

Can you maybe upload it on CurseForge? Otherwise you cant share it on the platfrom sadly :(

**Comment by SoulxluoS** [comment]
> Hi, just quick question.
> 
> 
> 
> Can you maybe upload it on CurseForge? Otherwise you cant share it on the platfrom sadly :(

No, A new mod with the same features is coming out this week. I advise you to use it.
https://discord.com/invite/rURmwrzUcz
