### ISSUE TITLE
CEM Official Vs cemFork Config File

### ISSUE THREAD

**Issue by bsteckroth** [SoulxluoS/cem_Fork#2]
First, thank you for making this. Second, I had a lot of trouble setting it up with your FA fork. While trouble shooting I noticed some others with the same issues on curse forge and forums, users trying to use your fork saying animal heads were in the ground and bodies rotated etc. same issue as my issue. After a few days trouble shooting, removing possible conflicting mods and and configs, I discovered that since I had already used the official CEM mod, it had written the config file. That was the problem. After deleting the original config file and allowing your fork to generate a new one everything was fixed. Thought I would just let you know. Maybe this is an isolated issue, but since you made an official README.md of the FA fork, maybe this is something to include in the cemFork ReadMe. "Delete original CEM config file" Just trying to help.

-BMO

**Comment by bsteckroth** [comment]
I'm an idiot. It's simply an option.
"use_new_model_creation_fix"=false
it needs to be turned off, and the hover tooltip says to please leave on. Let the world know this needs to be disabled for your amazing FA fork to work.

**Comment by SoulxluoS** [comment]
😉😄
