### ISSUE TITLE
Polar bear model bug

### ISSUE THREAD

**Issue by spunchbop121** [SoulxluoS/cem_Fork#3]
Latest S6 1.19.2
![image](https://user-images.githubusercontent.com/64424996/195695042-f088bd95-44d8-45bc-9061-dc0668cbfcf0.png)

CEM Config:
"use_new_model_creation_fix"=false
"use_old_animations"=false
"use_optifine_folder"=true

**Comment by SoulxluoS** [comment]
The problem here and the problem with the texture pack. You need to remove this one in polar_bear.jem model.
On the CEM side, it is beyond my power to change now. 
![Снимок экрана (60)](https://user-images.githubusercontent.com/70120313/195898910-7c309e76-a49e-400a-ac20-9f861400cb2a.png)
