### ISSUE TITLE
Change README.md to direct to the releases tab

### ISSUE THREAD

**Issue by Thanos1716** [SoulxluoS/cem_Fork#5]
To avoid confusion, it might be a good idea to change the text in the readme to link to the releases tab for this fork rather than the original Curseforge/Modrinth pages for the original, i.e. change
```Check out [Modrinth](https://modrinth.com/mod/cem) page, the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem), or build it yourself```
to 
```Check out the [Releases](https://github.com/YoungSoulluoS/cemFork/releases) page for builds, or build it yourself```

**Comment by SoulxluoS** [comment]
Okay, I will. Thank you
