### ISSUE TITLE
不支持

### ISSUE THREAD

**Issue by 54dsa** [SoulxluoS/cem_Fork#6]
Animatica does not support CEM
![QQ图片20221106122625](https://user-images.githubusercontent.com/116626829/200154215-589a0c3e-ba7e-44bb-b6a9-2d2fabeb36c0.png)

**Comment by SoulxluoS** [comment]
I haven't checked elsewhere, but working. Particularly for FA Addons Fork. The eyes blink.

**Comment by 54dsa** [comment]
I'm using the s8 version, the game version is 1.19.2, and the sheep's eyes turn into mosaics
![IMG_20221106_200239](https://user-images.githubusercontent.com/116626829/200169711-200482a3-fb82-4997-af5f-e12475280f23.jpg)
![FSVH{6Q`1R6%~FI`7$C Z 9](https://user-images.githubusercontent.com/116626829/200169747-8e0ff7c1-3f6e-41e9-8446-ebc698e6ebcc.png)
![JNFVP244@`SGA`)0GKR2}L5](https://user-images.githubusercontent.com/116626829/200169751-907c7478-f7d8-49a8-946b-bd36f97e2c42.png)

**Comment by SoulxluoS** [comment]
Testing now, and it really doesn't work.  Although it worked before. Looking for what the problem is and when it broke.

**Comment by 54dsa** [comment]
So how to solve it, will it be fixed in the next version

**Comment by SoulxluoS** [comment]
Okay, I found it. I disabled this setting (apparently like you). Need ON
![Inked2022-11-06_18 33 06](https://user-images.githubusercontent.com/70120313/200173898-52c2257d-cb2a-46e4-b529-771e02cd9bc8.jpg)

**Comment by 54dsa** [comment]
Sorry I don't have this option in my settings
![QQ图片20221107130458](https://user-images.githubusercontent.com/116626829/200230584-ead3f462-f69f-45f7-ab9c-b66b52a52631.png)

**Comment by 54dsa** [comment]
If I can't fix it, I look forward to the next release that can fix this

**Comment by SoulxluoS** [comment]
Install Animatica mod.

**Comment by 54dsa** [comment]
我试试

**Comment by 54dsa** [comment]
I tried the method you said, but it didn't work
![IMG_20221107_133632](https://user-images.githubusercontent.com/116626829/200234215-d9b9df26-a5a3-4839-b0b0-c24d8b9aaa9c.jpg)
![QQ图片20221107133600](https://user-images.githubusercontent.com/116626829/200234236-7cc107ee-4b50-4e5d-af3a-9398b1392bc6.png)

**Comment by 54dsa** [comment]
![IMG_20221107_133632](https://user-images.githubusercontent.com/116626829/200234308-b4978efe-a75f-4490-97b2-a250d8e19367.jpg)

**Comment by SoulxluoS** [comment]
Which texture pack is used?

**Comment by 54dsa** [comment]
These texture packs work perfectly in 1.19
![QQ图片20221107135635](https://user-images.githubusercontent.com/116626829/200236558-bcc22064-90e9-47f3-9c64-56de9f1846e3.png)

**Comment by SoulxluoS** [comment]
You have some kind of texture problem. It's not a CEM, FA or Animatica problem. I don't know how to help.

**Comment by 54dsa** [comment]
好吧

**Comment by 54dsa** [comment]
I've found the problem that it's not compatible with the RainbowPixel
