### ISSUE TITLE
[BUG] Witch arms rotation is cursed

### ISSUE THREAD

**Issue by Thanos1716** [SoulxluoS/cem_Fork#7]
**Version**

- [x] I am using the latest version of CEM

**Describe the bug**

The witch arms rotation matches Blockbench behaviour but not Optifine when the default Blockbench animation is applied.
When no animation is applied, the Optifine model appears to have two sets of arms, which if you ask me seems very cursed, and the CEM model appears to apply the rotation to the same set of arms twice.

**Expected behavior**

In terms of Optifine parity, I would expect there to be extra arms? I'm not sure because personally I think the blockbench version is the most correct, but it doesn't match Optifine.
Perhaps the best course of action would be Blockbench parity because that is what people are using to actually create the resourcepacks and what makes the most logical sense to me, or a setting (within the mod or even better within the resourcepack) which allows the user/developer to choose what type of parity they would like, and it defaults to the Optifine version if not specified

**Screenshots**
_With_ default blockbench animation on arms:
Optifine:
![2022-11-19_14 07 59](https://user-images.githubusercontent.com/80975570/202854732-684b049c-c7d5-4f81-bfab-807178c2c300.png)

CEM:
![2022-11-19_13 58 49](https://user-images.githubusercontent.com/80975570/202854333-c22a1cd0-dabc-4e22-9caf-67db6a7bf4b1.png)

Blockbench:
![Screenshot_20221119_133902](https://user-images.githubusercontent.com/80975570/202853813-0f76ef99-e523-43de-8976-d342e8bc2882.png)

_Without_ default blockbench animation on arms:

Optifine:
![2022-11-19_14 11 32](https://user-images.githubusercontent.com/80975570/202854920-5450963a-c2ab-418d-a7c8-1c95b2288523.png)

CEM:
![2022-11-19_13 56 21](https://user-images.githubusercontent.com/80975570/202854239-f67d6f63-cf71-42b1-908f-fc510ff7b49d.png)

Blockbench:
![Screenshot_20221119_135358](https://user-images.githubusercontent.com/80975570/202854149-77357478-9eaa-46fe-9cbd-b5a789278be2.png)

**Desktop:**

 - OS: Arch Linux
 - Java Version: openjdk 17.0.5 2022-10-18 (build 17.0.5+1)
 - Minecraft Version: 1.19.2

**Other**

I would also like to know if this type of issue is helpful, or if you are already aware of most of them and just need the time to fix them?

**Comment by SoulxluoS** [comment]
I know how to fix it, but don't plan to correct such errors. I only fix FA Fork related bugs. I am waiting for the CEM update.
Thank you

**Comment by Thanos1716** [comment]
I see, are you talking about an update to Optifines CEM or to dorianpbs CEM, and is there somewhere I can follow its development?

**Comment by Thanos1716** [comment]
@YoungSoulluoS

**Comment by SoulxluoS** [comment]
Dorianpb CEM, 
in Dorianpb discord or CEM mod GitHub

**Comment by Thanos1716** [comment]
Thank you! Forgot there was a discord
