### ISSUE TITLE
CEM crashes on 1.19.3

### ISSUE THREAD

**Issue by jonask028** [SoulxluoS/cem_Fork#8]
1.19.3

- [Y] I am using the latest version of CEM

**Describe the bug**

When I go to launch the game it crashes and brings up an error message about a missing field field_27709 during the mixin application process. Log is [here](https://mclo.gs/DaCJYhv) and relevant errors begin at line 547

**Expected behavior**

I expected it to at least launch the game without crashing. I know it hasn't been updated since 1.19.3 came out so i was expecting some issues with the allay and such. 

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS:Win11
 - Java Version:Java 17
 - Minecraft Version: 1.19.3

**Additional context**

I am using the Quilt loader but the errors don't seem to have anything to do with quilt. I also do have the ETF and animatica mods installed.

**Comment by SoulxluoS** [comment]
Hi, thank you.
Fixed in next update today.

**Comment by jonask028** [comment]
You are the bomb! Sorry if i made it seem like i was upset with you for the game not launching, i just didn't know how to describe it in detail and why it was an issue. Mad props and respect for your hard work my guy!
