### ISSUE TITLE
[BUG] issue

### ISSUE THREAD

**Issue by jonask028** [SoulxluoS/cem_Fork#9]
**Version**

- [X] I am using the latest version of CEM

**Describe the bug**

Sheep and horses are uh. Not looking great. sheep have their legs clipping through their body which is slanted and their head is a full block lower than the neck, picture attached.

**Expected behavior**

Sheep to have normal anatomy and cute little sheep ears

**Screenshots**

![image](https://user-images.githubusercontent.com/97471474/207948963-ce94d9be-6f7b-43f0-aa7e-0182f63aa35b.png)
There is no Optifine for 1.19.3

**Desktop (please complete the following information):**

 - OS: Win 11
 - Java Version: 17
 - Minecraft Version: 1.19.3 

**Additional context**
Pigs and cows are fine, so far all i've noticed is horses and sheep being messed up in similar ways. Horses just have the issues with their heads. I am using animatica and ETF on the quilt loader.

**Comment by SoulxluoS** [comment]
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17

**Comment by jonask028** [comment]
Oh my gosh i feel so dumb for not checking the FAQ first. Sorry about that, thank you!
